query groupSearch($first: Int, $after: String, $query: String!, $lat: Float!, $lon: Float!, $radius: Int, $source: [SearchSources!]!, $categoryId: Int) {
  results: keywordSearch(
    input: {first: $first, after: $after}
    filter: {query: $query, lat: $lat, lon: $lon, source: $source, radius: $radius, categoryId: $categoryId}
  ) {
    pageInfo {
      hasNextPage
      endCursor
      __typename
    }
    count
    edges {
      node {
        id
        result {
          ... on Group {
            ...BuildMeetupGroupSearch
            __typename
          }
          __typename
        }
        __typename
      }
      recommendationSource
      recommendationId
      __typename
    }
    __typename
  }
}

fragment BuildMeetupGroupSearch on Group {
  id
  name
  link
  description
  link
  city
  state
  country
  isPrivate
  groupPhoto {
    ...PhotoDetails
    __typename
  }
  stats {
    memberCounts {
      all
      __typename
    }
    __typename
  }
  __typename
}

fragment PhotoDetails on Image {
  id
  baseUrl
  preview
  __typename
}
