[package]
authors = ["Charanjit Singh <ckhabra@gmail.com>"]
edition = "2018"
name = "entropy"
version = "0.1.0"

[release]
target = "x86_64-unknown-linux-musl"

[dependencies]
tokio = { version = "*", features = ["full"] }
reqwest = { version =  "*", features = ["cookies", "gzip", "multipart", "json"] }
url = { version = "^2.2.2", features = ["serde"] }
serde = "*"
serde_json = "*"
urlencoding = "*"
scraper = "*"