[[poacher.meetup_com]]
coordinates = { lng = 30.75, lat= 76.78 }
search_terms = [
  "chandigarh",
  "tricity",
  "mohali",
  "punjab",
  "hack",
  "security"
]
radius = 70
blacklist.groups.slugs = [
  "Wander-Tribe",
  "Great-Himalayan-National-Park-Trekking-Meetup",
  "tgetravels-bangalore",
  "Chandigarh-Travel-Club",
  "GoAdventureOfficial",
  "tgetravels-bangalore",
  "Sudden-Plans-Bangalore-and-beyond",
  "bharatsthali-sarees",
  "thehtc"
]

[poacher.local]
groups.base_dir = "./groups"
events.base_dir = "./events"
