#+title: Entropy

Entropy is a [[https://hackerspaces.org/][hackerspace]] for technologists living in vicinity of Chandigarh,
physically or spiritually.

Entropy intends to shake things up in the tech scene of the city by providing an
open space for hackers of Chandigarh to identify and solve the problems they
deem fit.

* Initiatives

Here is a list of initiatives identifying problems, laying out plan for fixing
them, and status of what actions are being taken towards the solutions.

- [[./docs/initiatives/meager-tech-culture.org][Meager tech culture]]

  The first problem perhaps is lack of a tech culture in the city. Entropy will
  die down if there are no hackers to participate in it. This document documents
  one perspective on components of the problem, and propose certain solutions
  for them.

* RFCs

Not all ideas/problems are equal, some are too personal or poorly put together
to build an action plan for. Such thoughts should go through an RFC process,
where these problems are discussed, refined (ideally an action plan is drafted),
and if we can reach a consensus that we as a group want to associate with the
idea/problem-and-its-solution, then it is moved to [[./docs/initiatives][initiatives]].

* Chat 

- Matrix Space: https://matrix.to/#/!EJjSPytjXwjJyODGWC:matrix.org?via=matrix.org
- Telegram Group: https://t.me/joinchat/QiQGasCqA205OWM9
- Discord: https://discord.gg/y74NHawxTA

All the chat mediums are bridged, so you can connect to any one of them and communicate 
with the same group of people.
