CREATE TABLE meetup_groups (
  id VARCHAR PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  link VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  city VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  country VARCHAR NOT NULL,
  is_private BOOLEAN NOT NULL,
  member_count INTEGER NOT NULL,
  photo VARCHAR
)
