name: Re-build the entropy site

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  refresh:
    name: Re-poach events and rebuild entropy site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: entropy
          path: ./

      - run: |
          chmod +x ./entropy
          ./entropy poach meetup events --city Chandigarh -v
          ./entropy web build -v
        env:
          ENTROPY_STATIC_SITE: '{base_url="/entropy/"}'

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
